Imports System
Imports System.Data
Imports System.Text

Imports PDSA.Common
Imports PDSA.DataLayer
Imports PDSA.DataLayer.DataClasses
Imports PDSA.Validation

''' <summary>
''' This class calls the view vwStocksLookup
''' This class is generated by the Haystack Code Generator for .NET.
''' You should NOT modify this class as it is intended to be re-generated.
''' </summary>
Public Class vwStocksLookupData
  Inherits PDSADataClassReadOnly

#Region "Constructors"
  Public Sub New()
    MyBase.New()

    _Entity = New vwStocksLookup()

    Init()
  End Sub
  
  Public Sub New(ByVal dataProvider As PDSADataProvider, ByVal entity As vwStocksLookup)
    MyBase.New(dataProvider)

    _Entity = entity

    Init()
  End Sub
#End Region

#Region "Private Variables"
  Private _Entity As vwStocksLookup

  Private _WhereFilter As WhereFilters
  Private _OrderByFilter As OrderByFilters
  Private _SelectFilter As SelectFilters
  Private _RowCountFilter As RowCountFilters
#End Region

#Region "Filter Enumerations"
  ''' <summary>
  ''' Enumeration for selecting a SELECT statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum SelectFilters
    ''' <summary>
    ''' 'All' SelectFilter
    ''' </summary>
    All
    ''' <summary>
    ''' A Custom SelectFilter
    ''' </summary>
    Custom
  End Enum

  ''' <summary>
  ''' Enumeration for selecting a WHERE statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum WhereFilters
    ''' <summary>
    ''' No WhereFilter Selected
    ''' </summary>
    None
    ''' <summary>
    ''' A Custom WhereFilter
    ''' </summary>
    Custom
    ''' <summary>
    ''' 'barcode' WhereFilter
    ''' </summary>
    barcode
    ''' <summary>
    ''' 'Likebarcode' WhereFilter
    ''' </summary>
    Likebarcode
  End Enum

  ''' <summary>
  ''' Enumeration for selecting an ORDER BY statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum OrderByFilters
    ''' <summary>
    ''' No OrderByFilter Selected
    ''' </summary>
    None
    ''' <summary>
    ''' A Custom OrderByFilter
    ''' </summary>
    Custom
    ''' <summary>
    ''' 'barcode' OrderByFilter
    ''' </summary>
    barcode
  End Enum
  ''' <summary>
  ''' Enumeration for selecting a Row Count statement or Row Count stored procedure to execute when calling the RowCount() method.
  ''' </summary>
  Public Enum RowCountFilters
    ''' <summary>
    ''' 'All' RowCountFilter
    ''' </summary>
    All
    Custom
  End Enum
#End Region

#Region "Public Properties"
  ''' <summary>
  ''' Get/Set the Entity class that will be used to get and set properties/fields for this data class.
  ''' </summary>
  Public Property Entity() As vwStocksLookup
    Get
      Return _Entity
    End Get
    Set(ByVal value As vwStocksLookup)
      _Entity = value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a Dynamic SQL or Stored Procedure to execute to return data.
  ''' </summary>
  Public Property SelectFilter() As SelectFilters
    Get
      Return _SelectFilter
    End Get
    Set(ByVal Value As SelectFilters)
      _SelectFilter = Value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a WHERE clause to be used with a SELECT statement when using Dynamic SQL.
  ''' </summary>
  Public Property WhereFilter() As WhereFilters
    Get
      Return _WhereFilter
    End Get
    Set(ByVal Value As WhereFilters)
      _WhereFilter = Value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a ORDER BY clause to be used with a SELECT statement when using Dynamic SQL.
  ''' </summary>
  Public Property OrderByFilter() As OrderByFilters
    Get
      Return _OrderByFilter
    End Get
    Set(ByVal Value As OrderByFilters)
      _OrderByFilter = Value
    End Set
  End Property
  
  ''' <summary>
  ''' Get/Set a Row Count statement to execute when calling the RowCount() method. You might need to set a WhereFilter as well.
  ''' </summary>
  Public Property RowCountFilter() As RowCountFilters
    Get
      Return _RowCountFilter
    End Get
    Set(ByVal Value As RowCountFilters)
      _RowCountFilter = Value
    End Set
  End Property
#End Region

#Region "Init Method"
  ''' <summary>
  ''' Initializes this class to a valid start state.
  ''' </summary>
  Protected Overrides Sub Init()
    ClassName = "vwStocksLookupData"
    DBObjectName = "vwStocksLookup"
    SchemaName = "dbo"

    ' Create Data Columns
    InitDataColumns()
  End Sub
#End Region

#Region "InitDataColumns Method"
  ''' <summary>
  ''' Initializes all of the Data Columns with valid data for each field in the view.
  ''' </summary>
  Protected Overrides Sub InitDataColumns()
    Dim dc As PDSADataColumn

    ' Create each data column
    dc = PDSADataColumn.CreateDataColumn(vwStocksLookupData.ColumnNames.barcode, "barcode", False, GetType(String), DbType.String)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwStocksLookupData.ColumnNames.itemdesc, "item desc", False, GetType(String), DbType.String)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwStocksLookupData.ColumnNames.available, "available", False, GetType(Double), DbType.Double)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwStocksLookupData.ColumnNames.retail, "retail", False, GetType(Decimal), DbType.Decimal)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwStocksLookupData.ColumnNames.retail2, "retail2", False, GetType(Decimal), DbType.Decimal)
    AllColumns.Add(dc)
  End Sub
#End Region

#Region "EntityDataToColumnCollection Method"
  ''' <summary>
  ''' Moves the data from the Entity class into the Columns collection
  ''' </summary>
  Protected Overrides Sub EntityDataToColumnCollection()
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.barcode).SetAsNull = False Then
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.barcode).Value = Entity.barcode
    Else
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.barcode).Value = String.Empty
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.itemdesc).SetAsNull = False Then
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.itemdesc).Value = Entity.itemdesc
    Else
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.itemdesc).Value = String.Empty
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.available).SetAsNull = False Then
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.available).Value = Entity.available
    Else
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.available).Value = 0
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail).SetAsNull = False Then
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail).Value = Entity.retail
    Else
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail).Value = 0
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail2).SetAsNull = False Then
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail2).Value = Entity.retail2
    Else
      AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail2).Value = 0
    End If
    
  End Sub
#End Region

#Region "ColumnCollectionToEntityData Method"
  ''' <summary>
  ''' Moves the data from the Columns collection into the Entity class.
  ''' </summary>
  Protected Overrides Sub ColumnCollectionToEntityData()
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.barcode).IsNull = False Then
      Entity.barcode = AllColumns.GetByName(vwStocksLookupData.ColumnNames.barcode).GetAsString()
    Else
      Entity.barcode = String.Empty
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.itemdesc).IsNull = False Then
      Entity.itemdesc = AllColumns.GetByName(vwStocksLookupData.ColumnNames.itemdesc).GetAsString()
    Else
      Entity.itemdesc = String.Empty
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.available).IsNull = False Then
      Entity.available = AllColumns.GetByName(vwStocksLookupData.ColumnNames.available).GetAsDouble()
    Else
      Entity.available = 0
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail).IsNull = False Then
      Entity.retail = AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail).GetAsDecimal()
    Else
      Entity.retail = 0
    End If
    
    If AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail2).IsNull = False Then
      Entity.retail2 = AllColumns.GetByName(vwStocksLookupData.ColumnNames.retail2).GetAsDecimal()
    Else
      Entity.retail2 = 0
    End If
    
  End Sub
#End Region

#Region "CreateEntityFromDataRow Method"
  ''' <summary>
  ''' Creates an Entity object from a DataRow object.
  ''' </summary>
  ''' <param name="dr">DataRow object with all fields from the view in it.</param>
  ''' <returns>vwStocksLookup</returns>
  Public Function CreateEntityFromDataRow(ByVal dr As DataRow) As vwStocksLookup
    Dim entity As New vwStocksLookup()

    If dr.Table.Columns.Contains(vwStocksLookupData.ColumnNames.barcode) Then
      If dr(vwStocksLookupData.ColumnNames.barcode).Equals(DBNull.Value) = False Then
        entity.barcode = PDSAString.ConvertToStringTrim(dr(vwStocksLookupData.ColumnNames.barcode))
      End If
    End If
    If dr.Table.Columns.Contains(vwStocksLookupData.ColumnNames.itemdesc) Then
      If dr(vwStocksLookupData.ColumnNames.itemdesc).Equals(DBNull.Value) = False Then
        entity.itemdesc = PDSAString.ConvertToStringTrim(dr(vwStocksLookupData.ColumnNames.itemdesc))
      End If
    End If
    If dr.Table.Columns.Contains(vwStocksLookupData.ColumnNames.available) Then
      If dr(vwStocksLookupData.ColumnNames.available).Equals(DBNull.Value) = False Then
        entity.available = Convert.ToDouble(dr(vwStocksLookupData.ColumnNames.available))
      End If
    End If
    If dr.Table.Columns.Contains(vwStocksLookupData.ColumnNames.retail) Then
      If dr(vwStocksLookupData.ColumnNames.retail).Equals(DBNull.Value) = False Then
        entity.retail = Convert.ToDecimal(dr(vwStocksLookupData.ColumnNames.retail))
      End If
    End If
    If dr.Table.Columns.Contains(vwStocksLookupData.ColumnNames.retail2) Then
      If dr(vwStocksLookupData.ColumnNames.retail2).Equals(DBNull.Value) = False Then
        entity.retail2 = Convert.ToDecimal(dr(vwStocksLookupData.ColumnNames.retail2))
      End If
    End If
    entity.IsDirty = False

    Return entity
  End Function
#End Region

#Region "SelectSQL Method"
  ''' <summary>
  ''' Builds the SQL for the SELECT statement based on the SelectFilter property.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function SelectSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case SelectFilter
      Case SelectFilters.All
        sb.Append(" SELECT barcode, item_desc, available, retail, retail2 FROM dbo.vwStocksLookup")


      Case SelectFilters.Custom
        sb.Append(SelectCustom)

    End Select

    SQL = sb.ToString()

    Return SQL
  End Function
#End Region

#Region "RowCountSQL Method"
  ''' <summary>
  ''' Builds the SELECT Count(*) SQL that will count the number of rows.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function RowCountSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case RowCountFilter
      Case RowCountFilters.All
        sb.Append(" SELECT Count(*) As NumRecs FROM dbo.vwStocksLookup")


      Case RowCountFilters.Custom
        sb.Append(RowCountCustom)

    End Select

    sb.Append(WhereClauseSQL())

    SQL = sb.ToString()

    Return SQL
  End Function
#End Region

#Region "WhereClauseSQL Method"
  ''' <summary>
  ''' Builds the WHERE clause to be used in combination with a SELECT statement.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function WhereClauseSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case WhereFilter
      Case WhereFilters.Custom
        sb.Append(WhereCustom)

      Case WhereFilters.None
        ' Do nothing

      Case WhereFilters.barcode
        sb.Append(" WHERE barcode = @barcode")

        
      Case WhereFilters.Likebarcode
        sb.Append(" WHERE barcode LIKE @barcode")

        
    End Select

    Return sb.ToString()
  End Function
#End Region

#Region "WhereClauseFillInParameters Method"
  ''' <summary>
  ''' Builds the CommandObject.Parameters collection for any WHERE clause parameters.
  ''' </summary>
  Protected Overrides Sub WhereClauseFillInParameters()
    Select Case WhereFilter
      Case WhereFilters.barcode
        CommandObject.Parameters.Add(DataProvider.CreateParameter("barcode", DbType.String, Entity.barcode))
      Case WhereFilters.Likebarcode
        CommandObject.Parameters.Add(DataProvider.CreateParameter("barcode", DbType.String, Entity.barcode))

    End Select
  End Sub
#End Region

#Region "OrderByClauseSQL Method"
  ''' <summary>
  ''' Builds the ORDER BY clause to be used in combination with a SELECT statement.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function OrderByClauseSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case OrderByFilter
      Case OrderByFilters.None
        '  Do Nothing

      Case OrderByFilters.Custom
        sb.Append(OrderByCustom)

      Case OrderByFilters.barcode
          sb.Append(" ORDER BY barcode")


    End Select

    Return sb.ToString()
  End Function
#End Region

#Region "ColumnNames Class"
  ''' <summary>
  ''' Contains static string properties that represent the name of each property in the Product class.
  ''' This class is generated by the Haystack Code Generator for .NET.
  ''' Do not modify this class or add methods as it is intended to be able to be re-generated at any ti
  ''' </summary>
  Public Class ColumnNames
    ''' <summary>
    ''' Returns 'barcode'
    ''' </summary>
    Public Shared ReadOnly Property barcode() As String
      Get
        Return "barcode"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'item_desc'
    ''' </summary>
    Public Shared ReadOnly Property itemdesc() As String
      Get
        Return "item_desc"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'available'
    ''' </summary>
    Public Shared ReadOnly Property available() As String
      Get
        Return "available"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'retail'
    ''' </summary>
    Public Shared ReadOnly Property retail() As String
      Get
        Return "retail"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'retail2'
    ''' </summary>
    Public Shared ReadOnly Property retail2() As String
      Get
        Return "retail2"
      End Get
    End Property
  End Class
#End Region
End Class
