Imports System
Imports System.Data
Imports System.Text

Imports PDSA.Common
Imports PDSA.DataLayer
Imports PDSA.DataLayer.DataClasses
Imports PDSA.Validation

''' <summary>
''' This class calls the view vwSuspendDlvry
''' This class is generated by the Haystack Code Generator for .NET.
''' You should NOT modify this class as it is intended to be re-generated.
''' </summary>
Public Class vwSuspendDlvryData
  Inherits PDSADataClassReadOnly

#Region "Constructors"
  Public Sub New()
    MyBase.New()

    _Entity = New vwSuspendDlvry()

    Init()
  End Sub
  
  Public Sub New(ByVal dataProvider As PDSADataProvider, ByVal entity As vwSuspendDlvry)
    MyBase.New(dataProvider)

    _Entity = entity

    Init()
  End Sub
#End Region

#Region "Private Variables"
  Private _Entity As vwSuspendDlvry

  Private _WhereFilter As WhereFilters
  Private _OrderByFilter As OrderByFilters
  Private _SelectFilter As SelectFilters
  Private _RowCountFilter As RowCountFilters
#End Region

#Region "Filter Enumerations"
  ''' <summary>
  ''' Enumeration for selecting a SELECT statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum SelectFilters
    ''' <summary>
    ''' 'All' SelectFilter
    ''' </summary>
    All
    ''' <summary>
    ''' A Custom SelectFilter
    ''' </summary>
    Custom
  End Enum

  ''' <summary>
  ''' Enumeration for selecting a WHERE statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum WhereFilters
    ''' <summary>
    ''' No WhereFilter Selected
    ''' </summary>
    None
    ''' <summary>
    ''' A Custom WhereFilter
    ''' </summary>
    Custom
    ''' <summary>
    ''' 'Likesupplier' WhereFilter
    ''' </summary>
    Likesupplier
    ''' <summary>
    ''' 'supplier' WhereFilter
    ''' </summary>
    supplier
    ''' <summary>
    ''' 'employee' WhereFilter
    ''' </summary>
    employee
    ''' <summary>
    ''' 'SuspendID' WhereFilter
    ''' </summary>
    SuspendID
  End Enum

  ''' <summary>
  ''' Enumeration for selecting an ORDER BY statement when calling the Load, GetDataSet or GetDataReader method.
  ''' </summary>
  Public Enum OrderByFilters
    ''' <summary>
    ''' No OrderByFilter Selected
    ''' </summary>
    None
    ''' <summary>
    ''' A Custom OrderByFilter
    ''' </summary>
    Custom
    ''' <summary>
    ''' 'supplier' OrderByFilter
    ''' </summary>
    supplier
  End Enum
  ''' <summary>
  ''' Enumeration for selecting a Row Count statement or Row Count stored procedure to execute when calling the RowCount() method.
  ''' </summary>
  Public Enum RowCountFilters
    ''' <summary>
    ''' 'All' RowCountFilter
    ''' </summary>
    All
    Custom
  End Enum
#End Region

#Region "Public Properties"
  ''' <summary>
  ''' Get/Set the Entity class that will be used to get and set properties/fields for this data class.
  ''' </summary>
  Public Property Entity() As vwSuspendDlvry
    Get
      Return _Entity
    End Get
    Set(ByVal value As vwSuspendDlvry)
      _Entity = value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a Dynamic SQL or Stored Procedure to execute to return data.
  ''' </summary>
  Public Property SelectFilter() As SelectFilters
    Get
      Return _SelectFilter
    End Get
    Set(ByVal Value As SelectFilters)
      _SelectFilter = Value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a WHERE clause to be used with a SELECT statement when using Dynamic SQL.
  ''' </summary>
  Public Property WhereFilter() As WhereFilters
    Get
      Return _WhereFilter
    End Get
    Set(ByVal Value As WhereFilters)
      _WhereFilter = Value
    End Set
  End Property

  ''' <summary>
  ''' Get/Set a ORDER BY clause to be used with a SELECT statement when using Dynamic SQL.
  ''' </summary>
  Public Property OrderByFilter() As OrderByFilters
    Get
      Return _OrderByFilter
    End Get
    Set(ByVal Value As OrderByFilters)
      _OrderByFilter = Value
    End Set
  End Property
  
  ''' <summary>
  ''' Get/Set a Row Count statement to execute when calling the RowCount() method. You might need to set a WhereFilter as well.
  ''' </summary>
  Public Property RowCountFilter() As RowCountFilters
    Get
      Return _RowCountFilter
    End Get
    Set(ByVal Value As RowCountFilters)
      _RowCountFilter = Value
    End Set
  End Property
#End Region

#Region "Init Method"
  ''' <summary>
  ''' Initializes this class to a valid start state.
  ''' </summary>
  Protected Overrides Sub Init()
    ClassName = "vwSuspendDlvryData"
    DBObjectName = "vwSuspendDlvry"
    SchemaName = "dbo"

    ' Create Data Columns
    InitDataColumns()
  End Sub
#End Region

#Region "InitDataColumns Method"
  ''' <summary>
  ''' Initializes all of the Data Columns with valid data for each field in the view.
  ''' </summary>
  Protected Overrides Sub InitDataColumns()
    Dim dc As PDSADataColumn

    ' Create each data column
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.dridtmp, "dridtmp", False, GetType(Integer), DbType.Int32)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.drdate, "drdate", False, GetType(Date), DbType.Date)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.supplier, "supplier", False, GetType(String), DbType.String)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.supcode, "supcode", False, GetType(Integer), DbType.Int32)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.drdue, "drdue", False, GetType(Date), DbType.Date)
    AllColumns.Add(dc)
    dc = PDSADataColumn.CreateDataColumn(vwSuspendDlvryData.ColumnNames.sInsertid, "s Insert  id", False, GetType(String), DbType.String)
    AllColumns.Add(dc)
  End Sub
#End Region

#Region "EntityDataToColumnCollection Method"
  ''' <summary>
  ''' Moves the data from the Entity class into the Columns collection
  ''' </summary>
  Protected Overrides Sub EntityDataToColumnCollection()
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.dridtmp).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.dridtmp).Value = Entity.dridtmp
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.dridtmp).Value = 0
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdate).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdate).Value = Entity.drdate
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdate).Value = DateTime.Now
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supplier).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supplier).Value = Entity.supplier
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supplier).Value = String.Empty
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supcode).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supcode).Value = Entity.supcode
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supcode).Value = 0
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdue).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdue).Value = Entity.drdue
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdue).Value = DateTime.Now
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.sInsertid).SetAsNull = False Then
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.sInsertid).Value = Entity.sInsertid
    Else
      AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.sInsertid).Value = String.Empty
    End If
    
  End Sub
#End Region

#Region "ColumnCollectionToEntityData Method"
  ''' <summary>
  ''' Moves the data from the Columns collection into the Entity class.
  ''' </summary>
  Protected Overrides Sub ColumnCollectionToEntityData()
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.dridtmp).IsNull = False Then
      Entity.dridtmp = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.dridtmp).GetAsInteger()
    Else
      Entity.dridtmp = 0
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdate).IsNull = False Then
      Entity.drdate = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdate).GetAsDate()
    Else
      Entity.drdate = DateTime.Now
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supplier).IsNull = False Then
      Entity.supplier = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supplier).GetAsString()
    Else
      Entity.supplier = String.Empty
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supcode).IsNull = False Then
      Entity.supcode = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.supcode).GetAsInteger()
    Else
      Entity.supcode = 0
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdue).IsNull = False Then
      Entity.drdue = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.drdue).GetAsDate()
    Else
      Entity.drdue = DateTime.Now
    End If
    
    If AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.sInsertid).IsNull = False Then
      Entity.sInsertid = AllColumns.GetByName(vwSuspendDlvryData.ColumnNames.sInsertid).GetAsString()
    Else
      Entity.sInsertid = String.Empty
    End If
    
  End Sub
#End Region

#Region "CreateEntityFromDataRow Method"
  ''' <summary>
  ''' Creates an Entity object from a DataRow object.
  ''' </summary>
  ''' <param name="dr">DataRow object with all fields from the view in it.</param>
  ''' <returns>vwSuspendDlvry</returns>
  Public Function CreateEntityFromDataRow(ByVal dr As DataRow) As vwSuspendDlvry
    Dim entity As New vwSuspendDlvry()

    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.dridtmp) Then
      If dr(vwSuspendDlvryData.ColumnNames.dridtmp).Equals(DBNull.Value) = False Then
        entity.dridtmp = Convert.ToInt32(dr(vwSuspendDlvryData.ColumnNames.dridtmp))
      End If
    End If
    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.drdate) Then
      If dr(vwSuspendDlvryData.ColumnNames.drdate).Equals(DBNull.Value) = False Then
        entity.drdate = Convert.ToDateTime(dr(vwSuspendDlvryData.ColumnNames.drdate))
      End If
    End If
    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.supplier) Then
      If dr(vwSuspendDlvryData.ColumnNames.supplier).Equals(DBNull.Value) = False Then
        entity.supplier = PDSAString.ConvertToStringTrim(dr(vwSuspendDlvryData.ColumnNames.supplier))
      End If
    End If
    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.supcode) Then
      If dr(vwSuspendDlvryData.ColumnNames.supcode).Equals(DBNull.Value) = False Then
        entity.supcode = Convert.ToInt32(dr(vwSuspendDlvryData.ColumnNames.supcode))
      End If
    End If
    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.drdue) Then
      If dr(vwSuspendDlvryData.ColumnNames.drdue).Equals(DBNull.Value) = False Then
        entity.drdue = Convert.ToDateTime(dr(vwSuspendDlvryData.ColumnNames.drdue))
      End If
    End If
    If dr.Table.Columns.Contains(vwSuspendDlvryData.ColumnNames.sInsertid) Then
      If dr(vwSuspendDlvryData.ColumnNames.sInsertid).Equals(DBNull.Value) = False Then
        entity.sInsertid = PDSAString.ConvertToStringTrim(dr(vwSuspendDlvryData.ColumnNames.sInsertid))
      End If
    End If
    entity.IsDirty = False

    Return entity
  End Function
#End Region

#Region "SelectSQL Method"
  ''' <summary>
  ''' Builds the SQL for the SELECT statement based on the SelectFilter property.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function SelectSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case SelectFilter
      Case SelectFilters.All
        sb.Append(" SELECT dridtmp, drdate, supplier, supcode, drdue, sInsert_id FROM dbo.vwSuspendDlvry")


      Case SelectFilters.Custom
        sb.Append(SelectCustom)

    End Select

    SQL = sb.ToString()

    Return SQL
  End Function
#End Region

#Region "RowCountSQL Method"
  ''' <summary>
  ''' Builds the SELECT Count(*) SQL that will count the number of rows.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function RowCountSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case RowCountFilter
      Case RowCountFilters.All
        sb.Append(" SELECT Count(*) As NumRecs FROM dbo.vwSuspendDlvry")


      Case RowCountFilters.Custom
        sb.Append(RowCountCustom)

    End Select

    sb.Append(WhereClauseSQL())

    SQL = sb.ToString()

    Return SQL
  End Function
#End Region

#Region "WhereClauseSQL Method"
  ''' <summary>
  ''' Builds the WHERE clause to be used in combination with a SELECT statement.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function WhereClauseSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case WhereFilter
      Case WhereFilters.Custom
        sb.Append(WhereCustom)

      Case WhereFilters.None
        ' Do nothing

      Case WhereFilters.Likesupplier
        sb.Append(" WHERE supplier LIKE @supplier")

        
      Case WhereFilters.supplier
        sb.Append(" WHERE supplier = @supplier")

        
      Case WhereFilters.employee
        sb.Append(" WHERE sInsert_id  =  @sInsert_id")

        
      Case WhereFilters.SuspendID
        sb.Append(" WHERE dridtmp  =  @dridtmp")

        
    End Select

    Return sb.ToString()
  End Function
#End Region

#Region "WhereClauseFillInParameters Method"
  ''' <summary>
  ''' Builds the CommandObject.Parameters collection for any WHERE clause parameters.
  ''' </summary>
  Protected Overrides Sub WhereClauseFillInParameters()
    Select Case WhereFilter
      Case WhereFilters.Likesupplier
        CommandObject.Parameters.Add(DataProvider.CreateParameter("supplier", DbType.String, Entity.supplier))
      Case WhereFilters.supplier
        CommandObject.Parameters.Add(DataProvider.CreateParameter("supplier", DbType.String, Entity.supplier))
      Case WhereFilters.employee
        CommandObject.Parameters.Add(DataProvider.CreateParameter("sInsert_id", DbType.String, Entity.sInsertid))
      Case WhereFilters.SuspendID
        CommandObject.Parameters.Add(DataProvider.CreateParameter("dridtmp", DbType.Int32, Entity.dridtmp))

    End Select
  End Sub
#End Region

#Region "OrderByClauseSQL Method"
  ''' <summary>
  ''' Builds the ORDER BY clause to be used in combination with a SELECT statement.
  ''' </summary>
  ''' <returns>string</returns>
  Public Overrides Function OrderByClauseSQL() As String
    Dim sb As StringBuilder = New StringBuilder(SB_INIT_LENGTH)

    Select Case OrderByFilter
      Case OrderByFilters.None
        '  Do Nothing

      Case OrderByFilters.Custom
        sb.Append(OrderByCustom)

      Case OrderByFilters.supplier
          sb.Append(" ORDER BY supplier")


    End Select

    Return sb.ToString()
  End Function
#End Region

#Region "ColumnNames Class"
  ''' <summary>
  ''' Contains static string properties that represent the name of each property in the Product class.
  ''' This class is generated by the Haystack Code Generator for .NET.
  ''' Do not modify this class or add methods as it is intended to be able to be re-generated at any ti
  ''' </summary>
  Public Class ColumnNames
    ''' <summary>
    ''' Returns 'dridtmp'
    ''' </summary>
    Public Shared ReadOnly Property dridtmp() As String
      Get
        Return "dridtmp"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'drdate'
    ''' </summary>
    Public Shared ReadOnly Property drdate() As String
      Get
        Return "drdate"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'supplier'
    ''' </summary>
    Public Shared ReadOnly Property supplier() As String
      Get
        Return "supplier"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'supcode'
    ''' </summary>
    Public Shared ReadOnly Property supcode() As String
      Get
        Return "supcode"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'drdue'
    ''' </summary>
    Public Shared ReadOnly Property drdue() As String
      Get
        Return "drdue"
      End Get
    End Property
    ''' <summary>
    ''' Returns 'sInsert_id'
    ''' </summary>
    Public Shared ReadOnly Property sInsertid() As String
      Get
        Return "sInsert_id"
      End Get
    End Property
  End Class
#End Region
End Class
