Imports System
Imports System.Collections.Generic
Imports System.Linq

' This class is an extension of the additnlcash Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class additnlcash

#Region "RETURNVALUE Property"
  'Private mRETURNVALUE As Integer
  '
  'Public Property RETURNVALUE() As Integer
  '  Get
  '    Return mRETURNVALUE
  '  End Get
  '  Set(ByVal Value As Integer)
  '    If mRETURNVALUE <> Value Then
  '      mRETURNVALUE = Value
  '      RaisePropertyChanged("RETURNVALUE")
  '    End If
  '  End Set
  'End Property
#End Region
End Class

''' <summary>
''' This class is used when you wish to create a collection of additnlcash classes.
''' You may add additional methods to this class.
''' </summary>
Public Class additnlcashCollection
  Inherits List(Of additnlcash)

  Public Function Getadditnlcash(ByVal acid As Integer) As additnlcash
#If SILVERLIGHT Then
    Return First(Function(x) x.acid = acid)
#Else
    Return Find(Function(x) x.acid = acid)
#End If
    
  End Function
  
  ''' <summary>
  ''' Get all additnlcash objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of additnlcash Objects</returns>
  Public Function GetChanged() As List(Of additnlcash)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
