Imports System
Imports System.Collections.Generic
Imports System.Linq

' This class is an extension of the dlvry_hdr Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class dlvry_hdr

#Region "RETURNVALUE Property"
  'Private mRETURNVALUE As Integer
  '
  'Public Property RETURNVALUE() As Integer
  '  Get
  '    Return mRETURNVALUE
  '  End Get
  '  Set(ByVal Value As Integer)
  '    If mRETURNVALUE <> Value Then
  '      mRETURNVALUE = Value
  '      RaisePropertyChanged("RETURNVALUE")
  '    End If
  '  End Set
  'End Property
#End Region
End Class

''' <summary>
''' This class is used when you wish to create a collection of dlvry_hdr classes.
''' You may add additional methods to this class.
''' </summary>
Public Class dlvry_hdrCollection
  Inherits List(Of dlvry_hdr)

  Public Function Getdlvry_hdr(ByVal drid As Integer) As dlvry_hdr
#If SILVERLIGHT Then
    Return First(Function(x) x.drid = drid)
#Else
    Return Find(Function(x) x.drid = drid)
#End If
    
  End Function
  
  ''' <summary>
  ''' Get all dlvry_hdr objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of dlvry_hdr Objects</returns>
  Public Function GetChanged() As List(Of dlvry_hdr)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
