Imports System
Imports System.Collections.Generic
Imports System.Linq

' This class is an extension of the location Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class location

#Region "RETURNVALUE Property"
  'Private mRETURNVALUE As Integer
  '
  'Public Property RETURNVALUE() As Integer
  '  Get
  '    Return mRETURNVALUE
  '  End Get
  '  Set(ByVal Value As Integer)
  '    If mRETURNVALUE <> Value Then
  '      mRETURNVALUE = Value
  '      RaisePropertyChanged("RETURNVALUE")
  '    End If
  '  End Set
  'End Property
#End Region
End Class

''' <summary>
''' This class is used when you wish to create a collection of location classes.
''' You may add additional methods to this class.
''' </summary>
Public Class locationCollection
  Inherits List(Of location)

  Public Function Getlocation(ByVal locid As Integer) As location
#If SILVERLIGHT Then
    Return First(Function(x) x.locid = locid)
#Else
    Return Find(Function(x) x.locid = locid)
#End If
    
  End Function
  
  ''' <summary>
  ''' Get all location objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of location Objects</returns>
  Public Function GetChanged() As List(Of location)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
