Imports System
Imports System.Collections.Generic
Imports System.Linq

' This class is an extension of the posstocks Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class posstocks

#Region "RETURNVALUE Property"
  'Private mRETURNVALUE As Integer
  '
  'Public Property RETURNVALUE() As Integer
  '  Get
  '    Return mRETURNVALUE
  '  End Get
  '  Set(ByVal Value As Integer)
  '    If mRETURNVALUE <> Value Then
  '      mRETURNVALUE = Value
  '      RaisePropertyChanged("RETURNVALUE")
  '    End If
  '  End Set
  'End Property
#End Region
End Class

''' <summary>
''' This class is used when you wish to create a collection of posstocks classes.
''' You may add additional methods to this class.
''' </summary>
Public Class posstocksCollection
  Inherits List(Of posstocks)

  
  ''' <summary>
  ''' Get all posstocks objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of posstocks Objects</returns>
  Public Function GetChanged() As List(Of posstocks)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
