Imports System

' This class is an extension of the spGetReceiptNo Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class spGetReceiptNo

End Class
