Imports System
Imports PDSA.Validation

''' <summary>
''' This class contains properties for each data value returned, or parameter to be input/output from the spGetReplaceNo stored procedure.
''' This class is generated by the Haystack Code Generator for .NET.
''' Do not modify this class or add methods as it is intended to be able to be re-generated at any ti
''' </summary>
'<DataContract()> _
Partial Public Class spGetReplaceNo
   Inherits PDSAEntityBase

#Region "Constructor"
 Public Sub New()
    ClassName = "spGetReplaceNo"
 End Sub
#End Region

  #Region "Private Variables"
  Private _ReplaceNo As Integer = 0
  Private _RETURNVALUE As Integer = 0
#End Region

#Region "Public Properties"
  ''' <summary>
  ''' Get/Set the ReplaceNo value
  ''' </summary>
   _
  Public Property ReplaceNo() As Integer
    Get
      Return _ReplaceNo
    End Get
    Set(ByVal Value As Integer)
      If HasValueChanged(_ReplaceNo, Value, "@ReplaceNo") Then
        _ReplaceNo = Value
        RaisePropertyChanged("ReplaceNo")
      End If
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the RETURNVALUE value
  ''' </summary>
   _
  Public Property RETURNVALUE() As Integer
    Get
      Return _RETURNVALUE
    End Get
    Set(ByVal Value As Integer)
      If HasValueChanged(_RETURNVALUE, Value, "@RETURN_VALUE") Then
        _RETURNVALUE = Value
        RaisePropertyChanged("RETURNVALUE")
      End If
    End Set
  End Property
#End Region
End Class
