Imports System
Imports PDSA.Validation

''' <summary>
''' This class contains properties for each data value returned, or parameter to be input/output from the spTransferProc stored procedure.
''' This class is generated by the Haystack Code Generator for .NET.
''' Do not modify this class or add methods as it is intended to be able to be re-generated at any ti
''' </summary>
Partial Public Class spTransferProc
    Inherits PDSAEntityBase

#Region "Constructor"
    Public Sub New()
        ClassName = "spTransferProc"
    End Sub
#End Region

#Region "Private Variables"
    Private _tid As Integer = 0
    Private _RETURNVALUE As Integer = 0
#End Region

#Region "Public Properties"
    ''' <summary>
    ''' Get/Set the tid value
    ''' </summary>
   _
    Public Property tid() As Integer
        Get
            Return _tid
        End Get
        Set(ByVal Value As Integer)
            If HasValueChanged(_tid, Value, "@tid") Then
                _tid = Value
                RaisePropertyChanged("tid")
            End If
        End Set
    End Property
    ''' <summary>
    ''' Get/Set the RETURNVALUE value
    ''' </summary>
   _
    Public Property RETURNVALUE() As Integer
        Get
            Return _RETURNVALUE
        End Get
        Set(ByVal Value As Integer)
            If HasValueChanged(_RETURNVALUE, Value, "@RETURN_VALUE") Then
                _RETURNVALUE = Value
                RaisePropertyChanged("RETURNVALUE")
            End If
        End Set
    End Property
#End Region
End Class
