Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.Serialization

Imports PDSA.Validation

''' <summary>
''' This class contains properties for each data value that makes up a tbls.
''' This class is generated by the Haystack Code Generator for .NET.
''' Do not modify this class or add methods as it is intended to be able to be re-generated at any time.
''' </summary>
<DataContract()> _
Partial Public Class tbls
  Inherits PDSAEntityBase

#Region "Constructor"
  ''' <summary>
  ''' Constructor for the tbls class
  ''' </summary>
  Public Sub New()
    MyBase.New()
    
    ClassName = "tbls"
  End Sub
#End Region

  #Region "Private Variables"
  Private _tid As String = String.Empty
  Private _tdesc As String = String.Empty
#End Region

#Region "Public Properties"
  ''' <summary>
  ''' Get/Set the tid value
  ''' </summary>
  <DataMember()> _
  Public Property tid() As String
    Get
      Return _tid
    End Get
    Set(ByVal Value As String)
      If HasValueChanged(_tid, Value, "tid") Then
        _tid = Value
        RaisePropertyChanged("tid")
      End If
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the tdesc value
  ''' </summary>
  <DataMember()> _
  Public Property tdesc() As String
    Get
      Return _tdesc
    End Get
    Set(ByVal Value As String)
      If HasValueChanged(_tdesc, Value, "tdesc") Then
        _tdesc = Value
        RaisePropertyChanged("tdesc")
      End If
    End Set
  End Property
#End Region
End Class
