Imports System
Imports System.Runtime.Serialization

Imports PDSA.Validation

''' <summary>
''' This class contains properties for each data value that makes up a vwInvPayments.
''' This class is generated by the Haystack Code Generator for .NET.
''' Do not modify this class or add methods as it is intended to be able to be re-generated at any time.
''' </summary>
<DataContract()> _
Partial Public Class vwInvPayments
  Inherits PDSAEntityBase

#Region "Constructor"
  Public Sub New()
    ClassName = "vwInvPayments"
  End Sub
#End Region

  #Region "Private Variables"
  Private _payid As Integer = 0
  Private _paydate As Date = DateTime.Now
  Private _supcode As Integer = 0
  Private _amntpaid As Decimal = 0
  Private _supplier As String = String.Empty
  Private _chqno As String = String.Empty
  Private _bank As String = String.Empty
  Private _drinv As String = String.Empty
  Private _amnt As Decimal = 0
#End Region

#Region "Public Properties"
  ''' <summary>
  ''' Get/Set the payid value
  ''' </summary>
   _
  Public Property payid() As Integer
    Get
      Return _payid
    End Get
    Set(ByVal Value As Integer)
      _payid = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the paydate value
  ''' </summary>
   _
  Public Property paydate() As Date
    Get
      Return _paydate
    End Get
    Set(ByVal Value As Date)
      _paydate = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the supcode value
  ''' </summary>
   _
  Public Property supcode() As Integer
    Get
      Return _supcode
    End Get
    Set(ByVal Value As Integer)
      _supcode = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the amntpaid value
  ''' </summary>
   _
  Public Property amntpaid() As Decimal
    Get
      Return _amntpaid
    End Get
    Set(ByVal Value As Decimal)
      _amntpaid = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the supplier value
  ''' </summary>
   _
  Public Property supplier() As String
    Get
      Return _supplier
    End Get
    Set(ByVal Value As String)
      _supplier = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the chqno value
  ''' </summary>
   _
  Public Property chqno() As String
    Get
      Return _chqno
    End Get
    Set(ByVal Value As String)
      _chqno = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the bank value
  ''' </summary>
   _
  Public Property bank() As String
    Get
      Return _bank
    End Get
    Set(ByVal Value As String)
      _bank = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the drinv value
  ''' </summary>
   _
  Public Property drinv() As String
    Get
      Return _drinv
    End Get
    Set(ByVal Value As String)
      _drinv = Value
    End Set
  End Property
  ''' <summary>
  ''' Get/Set the amnt value
  ''' </summary>
   _
  Public Property amnt() As Decimal
    Get
      Return _amnt
    End Get
    Set(ByVal Value As Decimal)
      _amnt = Value
    End Set
  End Property
#End Region
End Class
