Imports System
Imports System.Linq

Imports PDSA.Validation

' This class is an extension of the vwPos Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.  
Partial Public Class vwPos

End Class

''' <summary>
''' This class is used when you wish to create a collection of vwPos classes.
''' You may add additional methods to this class.
''' </summary>
Public Class vwPosCollection
  Inherits List(Of vwPos)

  
  ''' <summary>
  ''' Get all vwPos objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of vwPos Objects</returns>
  Public Function GetChanged() As List(Of vwPos)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
