Imports System
Imports System.Linq

Imports PDSA.Validation

' This class is an extension of the vwReceipt Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.  
Partial Public Class vwReceipt

End Class

''' <summary>
''' This class is used when you wish to create a collection of vwReceipt classes.
''' You may add additional methods to this class.
''' </summary>
Public Class vwReceiptCollection
  Inherits List(Of vwReceipt)

  
  ''' <summary>
  ''' Get all vwReceipt objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of vwReceipt Objects</returns>
  Public Function GetChanged() As List(Of vwReceipt)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
