Imports System
Imports System.Collections.Generic
Imports System.Linq

' This class is an extension of the waiters Entity class
' This class is generated by the Haystack Code Generator for .NET.
' You may add additional properties to this class.
Partial Public Class waiters

#Region "RETURNVALUE Property"
  'Private mRETURNVALUE As Integer
  '
  'Public Property RETURNVALUE() As Integer
  '  Get
  '    Return mRETURNVALUE
  '  End Get
  '  Set(ByVal Value As Integer)
  '    If mRETURNVALUE <> Value Then
  '      mRETURNVALUE = Value
  '      RaisePropertyChanged("RETURNVALUE")
  '    End If
  '  End Set
  'End Property
#End Region
End Class

''' <summary>
''' This class is used when you wish to create a collection of waiters classes.
''' You may add additional methods to this class.
''' </summary>
Public Class waitersCollection
  Inherits List(Of waiters)

  Public Function Getwaiters(ByVal wtid As Integer) As waiters
#If SILVERLIGHT Then
    Return First(Function(x) x.wtid = wtid)
#Else
    Return Find(Function(x) x.wtid = wtid)
#End If
    
  End Function
  
  ''' <summary>
  ''' Get all waiters objects where IsDirty=True
  ''' </summary>
  ''' <returns>A List of waiters Objects</returns>
  Public Function GetChanged() As List(Of waiters)  
	  Return (From item In Me Where item.IsDirty = True).ToList()
  End Function
End Class
